# -*- coding: utf-8 -*-
"""log.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJ1mm3xdaD7Lv9ApgU73zt5aM7W7fs6e
"""

!pip install streamlit pyngrok openpyxl --quiet

import streamlit as st
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

st.title("Diabetes Prediction using Logistic Regression")

# ✅ Read Excel file directly from same folder (no upload needed)
dat = pd.read_excel("/content/diabetes.xlsx")  # make sure this file is in same folder

dat.head()

# Show data preview
st.subheader("Dataset Preview")
st.write(dat.head())

# Train the model
ind = dat[['age', 'plas', 'insu', 'mass']]
dep = dat['class']

model = LogisticRegression()
model.fit(ind, dep)

# Input fields
st.subheader("Enter Patient Data:")
age = st.number_input("Age", min_value=1, max_value=120, value=30)
plas = st.number_input("Plasma Glucose", min_value=0, max_value=200, value=100)
insu = st.number_input("Insulin", min_value=0, max_value=1000, value=100)
mass = st.number_input("Body Mass Index (BMI)", min_value=10.0, max_value=80.0, value=25.0)

# Prediction
if st.button("Predict"):
    result = model.predict([[age, plas, insu, mass]])
    if result[0] == 1:
        st.success("🎯 Prediction: Diabetic")
    else:
        st.success("💪 Prediction: Not Diabetic")

# Accuracy
st.subheader("Model Accuracy:")
pred_train = model.predict(ind)
acc = accuracy_score(dep, pred_train)
st.write(f"Accuracy: {acc:.2f}")