# -*- coding: utf-8 -*-
"""regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DuECE8CYTcYUxoXuwR1R8S15sVbj_of
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

!pip install openpyxl scikit-learn --quiet

df = pd.read_excel("diabetes.xlsx")  # File name must match exactly

df.head()

X = df[['age', 'plas', 'insu', 'mass']]  # Features
y = df['class']  # Target

model = LogisticRegression()
model.fit(X, y)
print("✅ Model trained successfully.")

print("\n🔎 Enter patient test data:")
age = int(input("Enter Age: "))
plas = int(input("Enter Plasma Glucose: "))
insu = int(input("Enter Insulin Level: "))
mass = float(input("Enter BMI (Mass): "))

prediction = model.predict([[age, plas, insu, mass]])

if prediction[0] == 1:
    print("\n🎯 Prediction: Diabetic")
else:
    print("\n💪 Prediction: Not Diabetic")

train_predictions = model.predict(X)
accuracy = accuracy_score(y, train_predictions)
print(f"📈 Training Accuracy: {accuracy:.2f}")