# -*- coding: utf-8 -*-
"""regress.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DuECE8CYTcYUxoXuwR1R8S15sVbj_of
"""

import streamlit as st
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

st.title("🩺 Diabetes Prediction using Logistic Regression")

# ✅ Load local file (must exist in GitHub repo)
df = pd.read_excel("/content/diabetes.xlsx")

df.head()

st.subheader("📊 Dataset Preview")
st.write(df.head())

X = df[['age', 'plas', 'insu', 'mass']]
y = df['class']

# Step 4: Train model
model = LogisticRegression()
model.fit(X, y)

st.subheader("👤 Enter Patient Information")
age = st.number_input("Age", 1, 120, 30)
plas = st.number_input("Plasma Glucose", 0, 200, 100)
insu = st.number_input("Insulin", 0, 1000, 100)
mass = st.number_input("BMI", 10.0, 80.0, 25.0)

if st.button("🔍 Predict"):
    prediction = model.predict([[age, plas, insu, mass]])
    if prediction[0] == 1:
        st.success("🎯 Prediction: Diabetic")
    else:
        st.success("💪 Prediction: Not Diabetic")

st.subheader("📈 Model Training Accuracy")
acc = accuracy_score(y, model.predict(X))
st.write(f"Accuracy: **{acc:.2f}**")